---
title: "Exploratory Data Analysis of Global Data from Gampminder in R"
output: github_document
author: "Hari Cheboyina"
---
###Gapminder Package Description:
* 1704 observations
* 6 variables
    + country: a factor with 142 levels
    + continent: a factor with 5 levels
    + year: going from 1952 to 2007 in increments of 5 years
    + pop: population
    + gdpPercap: GDP per capita
    + lifeExp: life expectancy

```{r, message = FALSE}
library(gapminder)
library(ggplot2)
library(dplyr)
gapminder %>%
  select(country, lifeExp, year, pop) %>%
  filter(country =="China" |
        country == "India") %>%
ggplot(aes(x=country, y=lifeExp, col=year, size=log(pop)))+
  geom_point(alpha=0.4)+
  geom_smooth(method=lm)
```

```{r}
gapminder %>%
  filter(gdpPercap<50000) %>%
  ggplot(aes(x=log(gdpPercap), y=lifeExp, col=year, size=pop))+
  geom_point(alpha=0.3)+
  geom_smooth(method=lm)+
  facet_wrap(~continent)
```

```{r}
gapminder %>%
  filter(year == 2007) %>%
  group_by(continent) %>%
  summarise(lifeExp = median(lifeExp))
```

```{r}
ggplot(gapminder, aes(x = continent, y = lifeExp)) +
  geom_boxplot(outlier.colour = "hotpink") +
  geom_jitter(position = position_jitter(width = 0.1, height = 0), alpha = 1/4)
```

```{r}
gap_with_colors <-
  data.frame(gapminder,
             cc = I(country_colors[match(gapminder$country,
                                         names(country_colors))]))

# bubble plot, focus just on Africa and Europe in 2007
keepers <- with(gap_with_colors,
                continent %in% c("Asia", "Europe") & year == 2007)
plot(lifeExp ~ gdpPercap, gap_with_colors,
     subset = keepers, log = "x", pch = 21,
     cex = sqrt(gap_with_colors$pop[keepers]/pi)/1500,
     bg = gap_with_colors$cc[keepers])

```

```{r}
ggplot(subset(gapminder, continent != "Americas"))+
       aes(x = year, y = lifeExp, group = country, color = country) +
  geom_line(lwd = 1, show.legend = FALSE) + facet_wrap(~ continent) +
  scale_color_manual(values = country_colors) +
  theme_bw() + theme(strip.text = element_text(size = rel(1.1)))
```